### PR TITLE
Added Spotify to YouTube Music bridge

### PR DESCRIPTION
**Pull request by BobbyESP**
I know this may not be added/merged, but I wanted to share it anyway.

I've made an API (that is public on my profile) that converts Spotify links into YouTube Music ones, so this is not illegal (not DRM bypassing). 
Hope you like it, thank you!

A screen recording of how it works:

https://user-images.githubusercontent.com/60316747/206874248-a2085d37-e0c4-4785-9abe-0481bfcb3000.mp4

### CODE REVIEW

**Comment by Marco-9456** [comment]
> I know this may not be added/merged, but I wanted to share it anyway.
> 
> I've made an API (that is public on my profile) that converts Spotify links into YouTube Music ones, so this is not illegal (not DRM bypassing). Hope you like it, thank you!
> 
> A screen recording of how it works:
> 
>  2022-12-10.21-32-44.mp4

This looks great.

**Comment by Marco-9456** [comment]
> I know this may not be added/merged, but I wanted to share it anyway.
> 
> I've made an API (that is public on my profile) that converts Spotify links into YouTube Music ones, so this is not illegal (not DRM bypassing). Hope you like it, thank you!
> 
> A screen recording of how it works:
> 
>  2022-12-10.21-32-44.mp4

This looks great.

Edited: When you paste an Album link
you'll get the usual yt-dlp error:

```
ERROR: [DRM] The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected
```

Here is the album link if you want to test on it: [Album](https://open.spotify.com/album/10nMiHzhAgAfy6rbHfpdUA?si=2e_dTEm0QsO5EUkDFE67wA&utm_source=copy-link)

> **Note**

I was using a custom command when i got this error, when using `save as audio` and `Download playlist` options the app will tell you that it couldn't fetch the video info and this bug will appear after that

https://user-images.githubusercontent.com/41828058/206884231-87b71c13-521f-4323-a212-370697af8120.mp4

**Comment by BobbyESP** [comment]
Yeah, i need to tell that actually I dont have in the API the support for Album/Playlists. Just tracks. Sorry, I'll be working on kr if needed.

**Comment by BobbyESP** [comment]
And yes, this needs to be polished

**Comment by BobbyESP** [comment]
Sorry for duplicated commits, my repo is kinda bugged 😢

**Comment by BobbyESP** [comment]
Another thing that I have to say is that the API is kinda slow because of the hosting... So it may take up to 15 seconds to reach the youtube url. I'll have to find another faster hosting. Heroku was great, but I think now is just paid.

**Comment by BobbyESP** [comment]
I'm doing a commit now. I've just ised my GitHub Student's developer pack Azure money for hosting the API kekw

**Comment by BobbyESP** [comment]
@JunkFood02 your thougts about this?

**Comment by JunkFood02** [comment]
Like what you said, this isn't going to be merged. The app should run reliably in native, and the API stuff is better for web applications. But thx for the good job & idea 🤞

**Comment by BobbyESP** [comment]
No problem! Thank you for reviewing it by the way! I really want to work in Seal to make it better and better :)

**Pull request closed without merging**
