### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Marco-9456**
This PR Aims to improve README

Edit: Done

### CODE REVIEW

**Comment by JunkFood02** [comment]
What's re-uploading screenshots for? I noticed an increase in the file size

**Comment by Marco-9456** [comment]
> What's re-uploading screenshots for? I noticed an increase in the file size

Ahh that's because i changed them,
Screenshot_20221020_073953

**Comment by JunkFood02** [comment]
🤣 I see. But I think we don't need to show every screen with dark/light themes. I'd like to revert these changes.

**Comment by Marco-9456** [comment]
> 🤣 I see. But I think we don't need to show every screen with dark/light themes. I'd like to revert these changes.

😂😂😂 Do as you like man

**Pull request merged**
