### PR TITLE
Update DownloadUtil.kt

### PR DESCRIPTION
**Pull request by the-loan-wolf**
the old string works but editor gives syntax error, i find this is the better way

### CODE REVIEW

**Comment by JunkFood02** [comment]
There is no error on my side with the latest version of Android Studio Canary
[Reference](https://kotlinlang.org/docs/strings.html#raw-strings)

**Comment by the-loan-wolf** [comment]
i was just reading the source with different editor that's why my editor was flagging it, ok i will close this PR and thank you for awesome APP

**Comment by the-loan-wolf** [comment]
Actually i tried that code in 2 different code editor and both showed error LOL

**Comment by JunkFood02** [comment]
IDEA (Android Studio) should be considered as the only standard editor(IDE) for Kotlin since it is developed by JetBrains

**Comment by the-loan-wolf** [comment]
Yes, but i was only reading the source in my free time and i don't like sitting in front of PC for that long

**Pull request closed without merging**
