### PR TITLE
Main README & README-ar Update.md

### PR DESCRIPTION
**Pull request by Marco-9456**
1. Finally managed to make README-ar completely RTL 👍🏼 
2. ~Made new Screenshots and put them inside a phone frame (Hope you like them 👀 ) .~ till v1.9.0 stable releases
3. All of the badges on the top are now flat instead of flat square.
4. aligned the `scroll to top` button in README-ar to the left.
5. changed the order of the upper part of the readme to the following;
   App icon
   app name
   Short description
   app Languages
   Badges

### CODE REVIEW

**Comment by JunkFood02** [comment]
LGTM.
But the UI is still under ongoing changes, so we'd better update the screenshots after v1.9.0 come to stable releases

**Comment by Marco-9456** [comment]
> LGTM 👍 

Glad you liked it.

But the UI is still under ongoing changes, so we'd better update the screenshots after v1.9.0 come to stable releases

Thanks for letting me know, should I close the pr and revert the screenshots changes and pr again or how should I do it?

**Comment by JunkFood02** [comment]
yes, you can revert the screenshots changes and i'll merge the rest of them

**Comment by Marco-9456** [comment]
Done (:

**Comment by Marco-9456** [comment]
Done (:

**Review by JunkFood02 — APPROVED** [review]

**Pull request merged**
