### PR TITLE
Better playlist management (again)

### PR DESCRIPTION
**Pull request by p3g4asus**
Hi,
I made again some changes in playlist management. Using the version in the current main branch, playlist download always shows the title and thumbnail of the first video of the playlist and is not stoppable. With the modifications of this PR, the thumbnail and the title of the current video download are showed and the user can stop the download at the end of each video. I added again the additional info text box under the thumbnail but it will be shown only when the debug preference is checked.

### CODE REVIEW

**Comment by JunkFood02** [comment]
Thanks for your hard work! I've done my modification on UI but haven't pushed and merge to main yet. So there would be some extra works to resolve new conflicts.

**Comment by p3g4asus** [comment]
Thank you for your nice app. It is a pleasure to help.

**Comment by p3g4asus** [comment]
I made an additional commit to fix two small bugs in the previous commits

**Comment by JunkFood02** [comment]
The main branch contains newest changes so you can do a rebase on it now. I would review & resolve these when having spare time.

**Comment by p3g4asus** [comment]
Rebase done. Thank you very much!

**Comment by JunkFood02** [comment]
Your code works like a charm! Thank you! It would take some take for me to finish my part migrating this function to fit in Seal's UI design, so stay tuned for new release. 😄

**Pull request merged**
