### PR TITLE
Implementation of Network/Connectivity Observer

### PR DESCRIPTION
**Pull request by BobbyESP**
Work in progress. The observer is already written but the UI implementation is just a mockup (even not implemented in real time updating {stateflow}).

https://user-images.githubusercontent.com/60316747/195695969-b400d301-d3ba-40bc-a66b-77fb7c4d7621.mp4

### CODE REVIEW

**Comment by BobbyESP** [comment]
I want to make appear at the bottom (or top) of the app like a popup telling you the new connectivity status (because this will only appear when the state is changed and for like 3 seconds).

**Comment by BobbyESP** [comment]
https://user-images.githubusercontent.com/60316747/195706881-fad3f1d6-fced-4534-9f8d-3164f62d8f6f.mp4

**Comment by BobbyESP** [comment]
Need to improve the timer

**Comment by esdnm** [comment]
This is completely unnecessary and it increases visual clutter.

**Comment by BobbyESP** [comment]
Maybe it is, but i have to say that i've started making this because i'm still learning kek.

**Pull request closed without merging**
