### PR TITLE
README in arabic

### PR DESCRIPTION
**Pull request by Marco-9456**
My fingers hurt

### CODE REVIEW

**Comment by JunkFood02** [comment]
Thx! 😂

**Comment by AI-IMED** [comment]
The alignment is supposed to be towards the right,
As shown in the picture:

**Comment by Marco-9456** [comment]
> The alignment is supposed to be towards the right, As shown in the picture:
> 
> 

I'm working on it, please be patient.

**Comment by AI-IMED** [comment]
Correct alignment has been implemented in Persian in the paragraph you mentioned earlier.

**Comment by Marco-9456** [comment]
> Correct alignment has been implemented in Persian in the paragraph you mentioned earlier.
> 
> 

I'll look into it

**Comment by Marco-9456** [comment]
@AI-IMED Done :)

**Comment by AI-IMED** [comment]
Thanks @Marco-9456 , I wonder if it is also possible to rearrange the objects shown in the image to adapt to the direction of RTL languages?

**Comment by Marco-9456** [comment]
> Thanks @Marco-9456 , I wonder if it is also possible to rearrange the objects shown in the image to adapt to the direction of RTL languages?
> 
> 

Sadly no, the star history one is only available in English and the weblate one is just like that from the source.

**Comment by AI-IMED** [comment]
OK, thank you Mohammed.

**Pull request merged**
