### PR TITLE
Fix for stop service button in notification

### PR DESCRIPTION
**Pull request by p3g4asus**
Now stop service button should only show when needed (during download task and when the app is unbound to the service). Using the button will cause the app to exit too.
I had to move service management under MainActivity class to make this work reliably (detect app stop and show service close button)

### CODE REVIEW

**Comment by JunkFood02** [comment]
Several fatal bugs would need some extra fixes:
1. When clicking the foreground service notification multiple times to open `MainActivity`, the application would crash due to `IllegalArgumentException: Service not registered` throws by `unBindService()`
2. When switching (swiping) between applications **over two times** would also cause the application to crash by the same Exception.
3. When doing such described in the second problem **twice**, although the application would not crash, the UI state would be cleared(?) like it just launched even though I've started a download process.
4. Clicking the video card still cannot open the video file being displayed currently.

**Comment by JunkFood02** [comment]
Also, I feel confused when reviewing code about the interaction between the `ViewModel` and the `Service`. I have no experience using `Messenger` or `LiveData`. And this is a small project for me to learn Modern Android Development and Jetpack Compose.

I think using [Kotlin Flow](https://developer.android.com/kotlin/flow) suggested by Android could fit in this use case better. Since all the data are produced in `Service` and passed to the `ViewModel`, then the `ViewModel` could process and pass the data to the UI. Doing this with Kotlin Flow would be natural, elegant, lifecycle-aware, and thread-safe with Kotlin Coroutine. Data could be encapsulated into a `StateFlow`, collected by ViewModel in a suspend function, then flow to the UI.

**Comment by JunkFood02** [comment]
According to [Android Developer Docs](https://developer.android.com/guide/components/bound-services), extending the `Binder` class could be a more straightforward solution for our use case. Since the service is just used in our application, running in the same process with `Activity` and does not need IPC stuff. Also, I think the Activity would not be killed separately from Service as they're in the same process.

[This article](https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb) may describe the advantages of `Flow` and `StateFlow` more clearly. In my practice, `Flow` could be used in many places, like the two Flows in `VideoListViewModel`. Data flows from the `RoomDatabase`, processed and collected by `ViewModel`, and then passed to the `Composable` for a reactive UI.

**Comment by p3g4asus** [comment]
> According to [Android Developer Docs](https://developer.android.com/guide/components/bound-services), extending the `Binder` class could be a more straightforward solution for our use case. Since the service is just used in our application, running in the same process with `Activity` and does not need IPC stuff. Also, I think the Activity would not be killed separately from Service as they're in the same process.
> 
> [This article](https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb) may describe the advantages of `Flow` and `StateFlow` more clearly. In my practice, `Flow` could be used in many places, like the two Flows in `VideoListViewModel`. Data flows from the `RoomDatabase`, processed and collected by `ViewModel`, and then passed to the `Composable` for a reactive UI.

The Activity and the service are in the same process as long as the Activity is not killed by the system. When you restart the Activity after it being killed by OS, it will not be in the same process. So, if you want to use ibinder, you need ipc and aidl. I think that messenger class is much simpler in our scenario. About convenience of using StateFlows over LiveDatas I agree as long as they are used to work with viewmodels that is where you used them in Seal.

**Comment by JunkFood02** [comment]
> The Activity and the service are in the same process as long as the Activity is not killed by the system. When you restart the Activity after it being killed by OS, it will not be in the same process.

`Activity` is just a component or a part of an application, the Android OS would kill the whole application as a process when needed. It would not kill or destroy just one Activity and leave other components like Service or other Activities to keep running in the process.

**Comment by JunkFood02** [comment]
> When a user close the app (accidentally or not) and then reopen it, the activity will reconnect to the service, show the progress again and allow you to add more task. If I change the implementation using binder without IPC and aidl, the app will reopen but will be unusable.

I think the example in Android Developer Docs just caused some misunderstanding here. Let's consider this use case again with some clarification and facts:
1. We need a (Foreground) `Service` to keep our application not being killed by the OS.
2. We need the `Service` to have a reliable connection with the `Activity` for updating UI and receiving events from the user.
3. The `Service` is not needed when not downloading and could be reopened when the user starts a new download task.
4. The `Activity` would not be "close" or destroyed by a user who accidentally presses the back button, unless they manually **kill the application** on purpose. It would enter the "Stop" stage of its lifecycle after the `onStop()` callback. The `Activity` or any other components would be and should be **always** in the **same process** (application process) with the `Service`, even if they're destroyed and recreated. This has nothing to do with IPC or AIDL.
5. The structure of Seal is quite simple indeed. Thus we don't need to unbind and rebind the `Service` to the `Activity` again and again. Unlike the example of music player service, the `Service` we use only binds to one `Activity`, and could be close safely after the download finishes.

Generally speaking, I think a Foreground [Bound Service](https://developer.android.com/guide/components/bound-services) could meet our satisfaction well. It only starts by `bindService()` with a download task and **only** unbinds and is destroyed when all the downloads finish. It prevents our application from killing by the OS only when downloading. When the application enters the background state and is not executing download tasks, it could be safely closed by the OS because the Service just stopped itself right after the download finishes. And It communicates with `Activity` with a simple `Binder` class because we do not need any IPC in a single process.

**Comment by JunkFood02** [comment]
After some further research, I think Foreground Service could be crucial for preventing the application from being killed, regardless of what work the Service is doing. As I described before, the Android OS kills the whole application process including all components in it. The key to restricting this action is to raise the priority of the process. We could do this by [putting the application in the foreground](https://developer.android.com/about/versions/oreo/background#services) by using the foreground service and [request for ignoring battery optimizations](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS).

**Pull request merged**
