### PR TITLE
Added the option to crop or not an audio cover. Closes #247

### LINKED ISSUE #247: an option on whether to crop the audio covers or not
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

In update 1.3.0 album art on audio was set to be cropped by default.

It would be really appreciated if a check box or something was added to let the user decide if it really should be cropped or not.

### Describe the solution you'd like

_No response_

### Video link

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BobbyESP**
As the title says. This don't affect to another areas of the app.

https://user-images.githubusercontent.com/60316747/192122292-b388aa0b-0b14-4980-beba-4038948542a0.mp4

### CODE REVIEW

**Comment by BobbyESP** [comment]
I should have created this in the dev branch, fck

**Comment by BobbyESP** [comment]
What about this? @JunkFood02

**Comment by rickdtc** [comment]
Why was this closed?

**Comment by BobbyESP** [comment]
Due to conflicts with the new version's code. If @JunkFood02 want to merge it i will recode it.

**Comment by BobbyESP** [comment]
@rickdtc Implemented in the new beta version

**Pull request closed without merging**
