### PR TITLE
Download in foreground service

### PR DESCRIPTION
**Pull request by JunkFood02**

### CODE REVIEW

**Comment by JunkFood02** [comment]
Some functions which not behave as expected I found so far:
1. When the user manually stops the foreground service and starts a new download task, should the service re-set itself to the foreground state again?
2. Sometimes the`openVideoFile()` function when clicking the video card would not open the correct video file properly. But I've not tested it much to locate where the problem causes.
3. When I clicked the stop icon in the foreground service notification while downloading, the download was not interrupted nor did the UI stop interaction with the service. Is this the expected behavior?

**Comment by p3g4asus** [comment]
I will make some test to answer you properly to the first and third issues. As for the second issue, clicking the video card will open the LAST completed video. This is the expected behavior. If you want, I can change it to make it download the CURRENT competed video (if exists).

**Comment by p3g4asus** [comment]
The 1st and 3rd issues are both caused by [this](https://developer.android.com/reference/android/content/Context#stopService(android.content.Intent)) behavior of stopService:
_Note that if a stopped service still has [ServiceConnection](https://developer.android.com/reference/android/content/ServiceConnection) objects bound to it with the [BIND_AUTO_CREATE](https://developer.android.com/reference/android/content/Context#BIND_AUTO_CREATE) set, it will not be destroyed until all of these bindings are removed. See the [Service](https://developer.android.com/reference/android/app/Service) documentation for more details on a service's lifecycle._
I will modify the code to effectively stop the service even if the app is bound, forcing it to unbind, or to refuse to close when the app is still bound. What is your preferred behavior?

**Comment by JunkFood02** [comment]
>As for the second issue, clicking the video card will open the LAST completed video. This is the expected behavior. If you want, I can change it to make it download the CURRENT competed video (if exists).

It would be good to do this because opening a video different from displaying one currently could confuse the user.

**Comment by JunkFood02** [comment]
> The 1st and 3rd issues are both caused by [this](https://developer.android.com/reference/android/content/Context#stopService(android.content.Intent)) behavior of stopService: _Note that if a stopped service still has [ServiceConnection](https://developer.android.com/reference/android/content/ServiceConnection) objects bound to it with the [BIND_AUTO_CREATE](https://developer.android.com/reference/android/content/Context#BIND_AUTO_CREATE) set, it will not be destroyed until all of these bindings are removed. See the [Service](https://developer.android.com/reference/android/app/Service) documentation for more details on a service's lifecycle._ I could modify the code to effectively stop the service even if the app is bound, forcing it to unbind and stopping the app too, or to refuse to close when the app is still bound. What is your preferred behavior?

I see. Since the service is needed for running all the time within the lifecycle of the application, the only reason a user would choose to close it should be that they want to force the download to stop. And it's not so useful for a user not being in the download process. 
So I think the "close" button should be only shown while the download process running, clicking it would force the application to quit. 
It's now clear that, as you described, the first problem arises because the service just called `stopForeground()` and didn't stop itself because of the existing `ServiceConnection`

**Comment by JunkFood02** [comment]
Thanks!

**Comment by p3g4asus** [comment]
One function is still missing. I am implementing the app exit on closing service now.

**Pull request merged**
