### PR TITLE
Implementation of thumbnail previsualization on pre-download popup

### PR DESCRIPTION
**Pull request by BobbyESP**
This is a video of how it works. By the moment is kinda slow because i just called the function before the one to open the settings popup. Just need to change one line to fix this, but changing that means that when opened the popup, the image will not be instatly loaded. A possible fix is just getting the video information once time, not one time to get the thumbnail for the settings popup and other one to the downloading stage (after pressing donwload in the popup)

Here is the demo

https://user-images.githubusercontent.com/60316747/182722526-499fde79-e2e9-47de-afb1-9765b4b61183.mp4

:

### CODE REVIEW

**Comment by Marco-9456** [comment]
This looks pretty good

**Comment by Marco-9456** [comment]
Are there any Artifacts that you can provide to test the build ?

**Comment by BobbyESP** [comment]
What are Artifacts? You can clone my repo and build it by yourself.
Sorry haha. If you can explain to me that about artifacts i will appreciate it.

**Comment by BobbyESP** [comment]
Ahh ok, now i know what you meant haha. I send you an apk file

**Comment by BobbyESP** [comment]
https://we.tl/t-qVRY1YRg1D

There they are. Sorry for the late haha

**Comment by Marco-9456** [comment]
> Ahh ok, now i know what you meant haha. I send you an apk file

Yeah an apk but in Github Action the apk is in a .zip file under a section called Artifacts.
i also don't wright in Englisch that much, so please forgive my poor grammar please

**Comment by Marco-9456** [comment]
> https://we.tl/t-qVRY1YRg1D
> 
> There they are. Sorry for the late haha

Lol my internet connection is so bad today, anyway thanks brother

**Comment by BobbyESP** [comment]
No problem! if you want tell me what arch you need and i send you only that one, nlt the full bundle

**Comment by BobbyESP** [comment]
> > Ahh ok, now i know what you meant haha. I send you an apk file
> 
> Yeah an apk but in Github Action the apk is in a .zip file under a section called Artifacts. i also don't wright in Englisch that much, so please forgive my poor grammar please

Noo, no problem, it's okay! And thanks for the info!

**Comment by Marco-9456** [comment]
> No problem! if you want tell me what arch you need and i send you only that one, not the full bundle

I am on arm64 v8 which is already included in the bundle, but thanks for asking anyway

**Comment by Marco-9456** [comment]
> > > Ahh ok, now i know what you meant haha. I send you an apk file
> > 
> > 
> > Yeah an apk but in Github Action the apk is in a .zip file under a section called Artifacts. i also don't wright in Englisch that much, so please forgive my poor grammar please
> 
> Noo, no problem, it's okay! And thanks for the info!

No problem :)

**Comment by JunkFood02** [comment]
Maybe a more natural practice is to fetch and show more info about the video on the main screen before downloading. But any changes made to download a single video process would cause its discontinuity with the operation logic of downloading playlists. And I want to make the whole process simple and intuitive. You can get more information in #93

**Comment by BobbyESP** [comment]
> Maybe a more natural practice is to fetch and show more info about the video on the main screen before downloading. But any changes made to download a single video process would cause its discontinuity with the operation logic of downloading playlists. And I want to make the whole process simple and intuitive. You can get more information in #93 

Okay! Thank you! Im having some ideas.

**Comment by JunkFood02** [comment]
Close this because I'm not planning to make changes to UI currently, but feel free to share your ideas in discussions

**Comment by BobbyESP** [comment]
Okay!

**Pull request closed without merging**
