### PR TITLE
Inapp updating

### PR DESCRIPTION
**Pull request by BobbyESP**
Im currently making this because it can be a great feature, but actual GitHub apk downloader libraries are quite bad...

WARNING! I've deleted title.txt file from fastlane folder because it caused problem with GIT. This branch cant be directly merged into main.

### CODE REVIEW

**Comment by BobbyESP** [comment]
The UI isn't also following the Material 3 rules because it's using Material 2 (you know, a bit old library). I recommend to rewrite the library but as a functionality of Seal so we don't need to depend of 3rd party libraries.

**Comment by BobbyESP** [comment]
The UI isn't also following the Material 3 rules because it's using Material 2 (you know, a bit old library). I recommend to rewrite the library but as a functionality of Seal so we don't need to depend of 3rd party libraries.

**Comment by JunkFood02** [comment]
#158 The problem with the `title.txt` is just an accident for its path being `title.txt `, fixed already

**Comment by BobbyESP** [comment]
Tuanks! I saw the issue before but didn't remember of it.

**Comment by JunkFood02** [comment]
I guess you're using [this library](https://github.com/hannesa2/githubAppUpdate). Since the release API is not very complicated, we can just implement it ourselves. Reference: [ReadYou](https://github.com/Ashinch/ReadYou/blob/main/app/src/main/java/me/ash/reader/data/repository/RYRepository.kt)

**Comment by BobbyESP** [comment]
Nice! And yes, that was the library

**Pull request closed without merging**
